services:
  notification-service:
    build:
      context: ../notification-service
      dockerfile: Dockerfile
    image: notification-service
    restart: always
    env_file:
      - .env
    environment:
      TZ: America/Sao_Paulo
      JAVA_TOOL_OPTIONS: >
        --enable-native-access=ALL-UNNAMED
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5082
    ports:
      - "8082:8082"
      - "5082:5082"
    mem_limit: 800m
    mem_reservation: 400m
    networks:
      - locadora-net

networks:
  locadora-net:
    external: true