server:
  port: 8082

spring:
  application:
    name: notification-service
  main:
    web-application-type: none
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "*"
    listener:
      ack-mode: manual
  mail:
    host: smtp.gmail.com # Ou o servidor SMTP da sua empresa/provedor (SendGrid, AWS SES)
    port: 587
    username: seu-email@dominio.com
    password: sua-senha-ou-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  kafka:
    topics:
      domain-events: ${APP_KAFKA_DOMAIN_EVENTS_TOPIC:videolocadora.domain-events}

web-client:
  connect-timeout-ms: ${WEBCLIENT_CONNECT_TIMEOUT_MS:3000}
  read-write-timeout-sec:  ${WEBCLIENT_READ_WRITE_TIMEOUT_SEC:10}
  response-timeout-sec: ${WEBCLIENT_RESPONSE_TIMEOUT_SEC:10}

management:
  endpoints:
    web:
      exposure:
        include: health,info
